version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VER=${APP_VER}
    image: jsettlers-server:${APP_VER}
    container_name: jsettlers-app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8880:8880"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.5.8
    container_name: ${DB_HOST}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
#      - "./jsettlers-${APP_VER}/src/main/bin/sql/jsettlers-create-mysql.sql:/docker-entrypoint-initdb.d/01-create-database.sql"
      - "./jsettlers-${APP_VER}/src/main/bin/sql/jsettlers-tables-mysql.sql:/docker-entrypoint-initdb.d/02-create-tables.sql"
      - "db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute 'SELECT 1;' $$MYSQL_DATABASE"
      start_period: 40s
      retries: 10
# Useful for debugging
#    command: --general-log=1 --general-log-file=/var/log/mysql/general-log.log

volumes:
  db_data:
