apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\cygwin64\usr\local\bin\kompose convert -f docker-compose-aks.yml
      -o deploy -v
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\cygwin64\usr\local\bin\kompose convert -f docker-compose-aks.yml
          -o deploy -v
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: app-env
        image: 'cr541779800.azurecr.io/jsettlers-server:2.4.00'
        imagePullPolicy: ""
        name: jsettlers-app
        ports:
        - containerPort: 8880
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
