---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\cygwin64\usr\local\bin\kompose convert -f docker-compose-aks.yml
      -o deploy -v
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: jsettlers-db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
