apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsettlers-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsettlers
      tier: app
  template:
    metadata:
      labels:
        app: jsettlers
        tier: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: app-env
        - secretRef:
            name: db-env
        image: mikakatua/jsettlers-server:2.6.10
        name: jsettlers-app
        ports:
        - containerPort: 8880
        resources: {}
        volumeMounts:
          - mountPath: /savegame
            name: app-data
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data
